name: hawaii_tcrum
channels: 
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - python=3.11.0
  - pip=23.0
  - pandas=1.5.3
  - googlemaps=2.5.1
  - selenium=4.7.2
  - snakemake=7.21.0
  - r-base=4.1.3
  - r-here=1.0.1
  - r-rmarkdown=2.20
  - r-tidyverse=1.3.2
  - r-stringr=1.5.0
  - r-leaflet=2.1.1
  - pip:
    - webdriver_manager==3.2.2
    


